services:
  authorunknown:
    image: ghcr.io/knaw-huc/service-huc-editor:2.0-rc9
    restart: unless-stopped
    environment:
      - BASE_URL=https://author-unknown.tt.di.huc.knaw.nl
    volumes:
      - ./data:/home/huc/huc-editor-service/data
    networks:
      - nginxproxynetwork

networks:
  nginxproxynetwork:
    external:
      name: nginxproxynetwork
